<?php 
return array (
  'site_name' => '集房经纪',
  'site_title' => '集房经纪',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://www.js-jifang.com',
  'site_my' => '集房经纪',
  'server_key' => 'efd8adeadf47ebd680e2a2be5bdc62ce',
  'site_chatkey' => '825174290f73c11f9d641f14a043a1aa',
  'server_topdomain' => 'weiwin.cc',
  'connectout' => '用户已到期，请联系管理员',
  'ischeckuser' => 'true',
  'reg_needmp' => 'false',
  'reg_groupid' => '4',
  'reg_validdays' => '100',
  'ipc' => '浙IPC备12587号',
  'site_qq' => '76020694',
  'site_mp' => '12345678911',
  'baidu_map_api' => 'VvtbHOtv7fAmn45bQ7W5wwkI',
  'site_email' => '76020694@qq.com',
  'keyword' => '集房经纪',
  'content' => '集房经纪',
  'countsz' => '',
  'copyright' => '集房经纪',
);